### ISSUE TITLE
Fluxo de cursos e regras

### ISSUE THREAD

**Issue by muniz95** [openschoolbr/sobre#1]
Salve!

Atualizei o README com as ideias que eu tive a respeito da confecção dos cursos, desde a proposta de tema até encerramento, e como proceder em cada fase.

Escrevi tudo que me veio na cabeça pensando num fluxo pra esses cursos, então pode ter uma ou outra besteira la. 
Aqui pode ser um brainstorm pra melhorar esse doc também

**Comment by khaosdoctor** [comment]
Fizemos as alterações no README aqui para deixar o modelo mais finalizado, você pode comentar lá na #11 se você acha que está de acordo, @muniz95? Ai eu fecho esse issue aqui e movemos pra lá :D
